import AuthProvider from "@/context/auth-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          "w-screen min-h-screen bg-[#242424] flex flex-col items-center justify-center"
        }
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
